### ISSUE TITLE
Not working in Windows 11 23H2

### ISSUE THREAD

**Issue by brande77** [mrsilver76/Logitech-F710-Windows-driver#2]
This doesn't seem to be working on the current version of Windows 11.
Here is how it appears now in Device Manager:
![image](https://github.com/user-attachments/assets/cbe306a9-1020-43e4-a5a8-2ae6d552cc17)

Attempting to continue with the installation of the modified driver results in:
![image](https://github.com/user-attachments/assets/4b69cde7-40a8-4953-b4c4-6f2c6e8aefc8)
Driver signing is disabled.
![image](https://github.com/user-attachments/assets/b5f44885-635c-42ae-8115-4fa0d3ff3adb)

**Comment by mrsilver76** [comment]
I’m going to struggle to be much help as I didn’t write the driver. I’m running W11 but not 23H2 so I’ll uninstall the drivers, apply the update and try myself. 

It won’t be for a little over a week I’m afraid, but I’ll report back. Feel free to prod me if you don’t hear after about 10 days.

**Comment by mrsilver76** [comment]
Sorry for the delay in coming back to you.

I'm on 23H2 and it installed just fine. The device appeared as Wireless Gamepad F710 first and then, after rebooting, I was able to point Device Manager to the folder and it installed the drivers just fine. Do you have the controller in X-Input mode?

I suspect that your problem is the "Device Descriptor Request Failed" issue. Do you have a dodgy cable? Are you connected through a USB hub rather than directly into the PC?

Sorry I cannot be much more help.

**Comment by brande77** [comment]
Thanks for testing it out. There is no cable since the F710 is wireless and I plugged the dongle directly into my laptop. Perhaps the dongle died somehow. I will bring it to my relative's home and test it on their Win 10 PC to see what happens.

**Comment by brande77** [comment]
After testing on a couple of other machines, it looks like it's just a case of a dongle that has gone bad and doesn't work in anything anymore. Thanks for checking also!
